packages:
  - "apps/web"
allowBuilds:
  '@firebase/util': set this to true or false
  protobufjs: set this to true or false
  sharp: set this to true or false
fetchRetries: 8
fetchRetryMaxtimeout: 300000
fetchTimeout: 600000
