"""project synopsis and declared asset language

Revision ID: e603ea832ab7
Revises: f9ad441e11aa
Created: 2026-08-26 00:14:54.151777+00:00
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = 'e603ea832ab7'
down_revision: str | None = 'f9ad441e11aa'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assets', sa.Column('declared_language', sa.String(length=20), nullable=True))
    op.add_column('projects', sa.Column('synopsis', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'synopsis')
    op.drop_column('assets', 'declared_language')
    # ### end Alembic commands ###
