"""rule dispositions

Revision ID: b20e35946380
Revises: e603ea832ab7
Created: 2026-08-26 00:26:48.424627+00:00
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = 'b20e35946380'
down_revision: str | None = 'e603ea832ab7'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rule_dispositions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('rule_id', sa.UUID(), nullable=False),
    sa.Column('decided_by', sa.UUID(), nullable=False),
    sa.Column('action', sa.String(length=20), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("action IN ('accept','set_aside')", name='ck_disposition_action'),
    sa.CheckConstraint('length(trim(reason)) > 0', name='ck_disposition_has_reason'),
    sa.ForeignKeyConstraint(['decided_by'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['rule_id'], ['rules.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'rule_id', name='uq_disposition_per_rule')
    )
    op.create_index(op.f('ix_rule_dispositions_project_id'), 'rule_dispositions', ['project_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rule_dispositions_project_id'), table_name='rule_dispositions')
    op.drop_table('rule_dispositions')
    # ### end Alembic commands ###
