"""initial schema

Revision ID: 1e5a04519069
Revises: 
Created: 2026-08-25 02:10:20.116738+00:00
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '1e5a04519069'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('destinations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('official_domain', sa.String(length=255), nullable=True),
    sa.Column('public', sa.Boolean(), nullable=False),
    sa.Column('requires_private_spec', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('auth_subject', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('auth_subject')
    )
    op.create_table('projects',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('project_type', sa.String(length=50), nullable=False),
    sa.Column('primary_language', sa.String(length=20), nullable=True),
    sa.Column('runtime_seconds', sa.Integer(), nullable=True),
    sa.Column('country_of_origin', sa.String(length=2), nullable=True),
    sa.Column('internal_code', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_owner_id'), 'projects', ['owner_id'], unique=False)
    op.create_table('rule_packs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('destination_id', sa.UUID(), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('schema_version', sa.String(length=20), nullable=False),
    sa.Column('digest', sa.String(length=64), nullable=False),
    sa.Column('extraction_model', sa.String(length=120), nullable=True),
    sa.Column('prompt_version', sa.String(length=40), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['destination_id'], ['destinations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('destination_id', 'version', 'owner_id', name='uq_rule_pack_version')
    )
    op.create_index(op.f('ix_rule_packs_destination_id'), 'rule_packs', ['destination_id'], unique=False)
    op.create_table('source_evidence',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('destination_id', sa.UUID(), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=True),
    sa.Column('source_type', sa.String(length=40), nullable=False),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source_hash', sa.String(length=64), nullable=False),
    sa.Column('quoted_excerpt', sa.Text(), nullable=False),
    sa.Column('trust_tier', sa.String(length=1), nullable=False),
    sa.Column('private', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("trust_tier IN ('A','B','C','D')", name='ck_source_evidence_tier'),
    sa.CheckConstraint('(private = false) OR (owner_id IS NOT NULL AND url IS NULL)', name='ck_private_spec_is_owned_and_unpublished'),
    sa.ForeignKeyConstraint(['destination_id'], ['destinations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_source_evidence_dest_hash', 'source_evidence', ['destination_id', 'source_hash'], unique=False)
    op.create_index(op.f('ix_source_evidence_destination_id'), 'source_evidence', ['destination_id'], unique=False)
    op.create_table('approvals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('repair_plan_digest', sa.String(length=64), nullable=False),
    sa.Column('approved_step_ids_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'repair_plan_digest', name='uq_approval_plan_digest')
    )
    op.create_index(op.f('ix_approvals_project_id'), 'approvals', ['project_id'], unique=False)
    op.create_table('assets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=40), nullable=False),
    sa.Column('original_filename', sa.String(length=500), nullable=False),
    sa.Column('storage_key', sa.String(length=700), nullable=False),
    sa.Column('content_type', sa.String(length=120), nullable=False),
    sa.Column('byte_size', sa.BigInteger(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=True),
    sa.Column('immutable', sa.Boolean(), nullable=False),
    sa.Column('custody_state', sa.String(length=40), nullable=False),
    sa.Column('derived_from_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('byte_size >= 0', name='ck_assets_byte_size_non_negative'),
    sa.ForeignKeyConstraint(['derived_from_id'], ['assets.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assets_project_id'), 'assets', ['project_id'], unique=False)
    op.create_index('ix_assets_project_role', 'assets', ['project_id', 'role'], unique=False)
    op.create_index(op.f('ix_assets_sha256'), 'assets', ['sha256'], unique=False)
    op.create_table('deletion_requests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('requested_by', sa.UUID(), nullable=False),
    sa.Column('state', sa.String(length=20), nullable=False),
    sa.Column('objects_total', sa.Integer(), nullable=False),
    sa.Column('objects_deleted', sa.Integer(), nullable=False),
    sa.Column('error_code', sa.String(length=80), nullable=True),
    sa.Column('requested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requested_by'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deletion_requests_project_id'), 'deletion_requests', ['project_id'], unique=False)
    op.create_table('jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('idempotency_key', sa.String(length=120), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('state', sa.String(length=20), nullable=False),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_code', sa.String(length=80), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'idempotency_key', name='uq_job_idempotency')
    )
    op.create_index(op.f('ix_jobs_project_id'), 'jobs', ['project_id'], unique=False)
    op.create_table('packages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('destination_id', sa.UUID(), nullable=False),
    sa.Column('rule_pack_id', sa.UUID(), nullable=False),
    sa.Column('state', sa.String(length=20), nullable=False),
    sa.Column('storage_key', sa.String(length=700), nullable=True),
    sa.Column('sha256', sa.String(length=64), nullable=True),
    sa.Column('manifest_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('validated_against_output', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("state <> 'VERIFIED' OR (sha256 IS NOT NULL AND manifest_json IS NOT NULL AND validated_against_output = true)", name='ck_verified_requires_proof'),
    sa.ForeignKeyConstraint(['destination_id'], ['destinations.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['rule_pack_id'], ['rule_packs.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_packages_project_id'), 'packages', ['project_id'], unique=False)
    op.create_table('passports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('digest', sa.String(length=64), nullable=False),
    sa.Column('passport_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'version', name='uq_passport_version')
    )
    op.create_index(op.f('ix_passports_project_id'), 'passports', ['project_id'], unique=False)
    op.create_table('preflight_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('rule_pack_set_digest', sa.String(length=64), nullable=False),
    sa.Column('comparison_digest', sa.String(length=64), nullable=True),
    sa.Column('state', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_preflight_runs_project_id'), 'preflight_runs', ['project_id'], unique=False)
    op.create_table('rules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('rule_pack_id', sa.UUID(), nullable=False),
    sa.Column('asset_type', sa.String(length=30), nullable=False),
    sa.Column('field', sa.String(length=60), nullable=False),
    sa.Column('operator', sa.String(length=20), nullable=False),
    sa.Column('expected_value_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('source_evidence_id', sa.UUID(), nullable=False),
    sa.Column('confidence', sa.String(length=10), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.CheckConstraint("confidence IN ('high','medium','low')", name='ck_rules_confidence'),
    sa.CheckConstraint("severity IN ('required','recommended','context')", name='ck_rules_severity'),
    sa.ForeignKeyConstraint(['rule_pack_id'], ['rule_packs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_evidence_id'], ['source_evidence.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rules_rule_pack_id'), 'rules', ['rule_pack_id'], unique=False)
    op.create_table('asset_evidence',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('asset_id', sa.UUID(), nullable=False),
    sa.Column('inspector', sa.String(length=80), nullable=False),
    sa.Column('inspector_version', sa.String(length=80), nullable=False),
    sa.Column('schema_version', sa.String(length=20), nullable=False),
    sa.Column('measured_properties_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('raw_private_evidence_key', sa.String(length=700), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_asset_evidence_asset_id'), 'asset_evidence', ['asset_id'], unique=False)
    op.create_table('delivery_rooms',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('package_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('recipient_label', sa.String(length=200), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['package_id'], ['packages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index(op.f('ix_delivery_rooms_package_id'), 'delivery_rooms', ['package_id'], unique=False)
    op.create_table('repair_plans',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('preflight_run_id', sa.UUID(), nullable=False),
    sa.Column('digest', sa.String(length=64), nullable=False),
    sa.Column('state', sa.String(length=30), nullable=False),
    sa.Column('estimated_seconds', sa.Integer(), nullable=True),
    sa.Column('estimated_cost_minor', sa.Integer(), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['preflight_run_id'], ['preflight_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'digest', name='uq_repair_plan_digest')
    )
    op.create_index(op.f('ix_repair_plans_project_id'), 'repair_plans', ['project_id'], unique=False)
    op.create_table('assertions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('preflight_run_id', sa.UUID(), nullable=False),
    sa.Column('destination_id', sa.UUID(), nullable=False),
    sa.Column('asset_id', sa.UUID(), nullable=True),
    sa.Column('rule_id', sa.UUID(), nullable=False),
    sa.Column('measured_value_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('result', sa.String(length=20), nullable=False),
    sa.Column('evidence_id', sa.UUID(), nullable=True),
    sa.Column('is_output_validation', sa.Boolean(), nullable=False),
    sa.CheckConstraint("result IN ('PASS','REPAIRABLE','REVIEW_REQUIRED','UNSUPPORTED','AMBIGUOUS','NOT_MEASURED')", name='ck_assertions_result'),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['destination_id'], ['destinations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['evidence_id'], ['asset_evidence.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['preflight_run_id'], ['preflight_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['rule_id'], ['rules.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assertions_preflight_run_id'), 'assertions', ['preflight_run_id'], unique=False)
    op.create_table('delivery_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('delivery_room_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(length=40), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('safe_metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.CheckConstraint("event_type IN ('OPENED','DOWNLOAD_STARTED','DOWNLOAD_COMPLETED','DENIED')", name='ck_delivery_event_type'),
    sa.ForeignKeyConstraint(['delivery_room_id'], ['delivery_rooms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_delivery_events_delivery_room_id'), 'delivery_events', ['delivery_room_id'], unique=False)
    op.create_table('repair_steps',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('repair_plan_id', sa.UUID(), nullable=False),
    sa.Column('operation', sa.String(length=60), nullable=False),
    sa.Column('safety_level', sa.String(length=10), nullable=False),
    sa.Column('input_asset_id', sa.UUID(), nullable=True),
    sa.Column('output_role', sa.String(length=40), nullable=False),
    sa.Column('parameters_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('dependency_ids_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('state', sa.String(length=30), nullable=False),
    sa.CheckConstraint("safety_level IN ('green','yellow','red')", name='ck_repair_safety'),
    sa.ForeignKeyConstraint(['input_asset_id'], ['assets.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['repair_plan_id'], ['repair_plans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_repair_steps_repair_plan_id'), 'repair_steps', ['repair_plan_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_repair_steps_repair_plan_id'), table_name='repair_steps')
    op.drop_table('repair_steps')
    op.drop_index(op.f('ix_delivery_events_delivery_room_id'), table_name='delivery_events')
    op.drop_table('delivery_events')
    op.drop_index(op.f('ix_assertions_preflight_run_id'), table_name='assertions')
    op.drop_table('assertions')
    op.drop_index(op.f('ix_repair_plans_project_id'), table_name='repair_plans')
    op.drop_table('repair_plans')
    op.drop_index(op.f('ix_delivery_rooms_package_id'), table_name='delivery_rooms')
    op.drop_table('delivery_rooms')
    op.drop_index(op.f('ix_asset_evidence_asset_id'), table_name='asset_evidence')
    op.drop_table('asset_evidence')
    op.drop_index(op.f('ix_rules_rule_pack_id'), table_name='rules')
    op.drop_table('rules')
    op.drop_index(op.f('ix_preflight_runs_project_id'), table_name='preflight_runs')
    op.drop_table('preflight_runs')
    op.drop_index(op.f('ix_passports_project_id'), table_name='passports')
    op.drop_table('passports')
    op.drop_index(op.f('ix_packages_project_id'), table_name='packages')
    op.drop_table('packages')
    op.drop_index(op.f('ix_jobs_project_id'), table_name='jobs')
    op.drop_table('jobs')
    op.drop_index(op.f('ix_deletion_requests_project_id'), table_name='deletion_requests')
    op.drop_table('deletion_requests')
    op.drop_index(op.f('ix_assets_sha256'), table_name='assets')
    op.drop_index('ix_assets_project_role', table_name='assets')
    op.drop_index(op.f('ix_assets_project_id'), table_name='assets')
    op.drop_table('assets')
    op.drop_index(op.f('ix_approvals_project_id'), table_name='approvals')
    op.drop_table('approvals')
    op.drop_index(op.f('ix_source_evidence_destination_id'), table_name='source_evidence')
    op.drop_index('ix_source_evidence_dest_hash', table_name='source_evidence')
    op.drop_table('source_evidence')
    op.drop_index(op.f('ix_rule_packs_destination_id'), table_name='rule_packs')
    op.drop_table('rule_packs')
    op.drop_index(op.f('ix_projects_owner_id'), table_name='projects')
    op.drop_table('projects')
    op.drop_table('users')
    op.drop_table('destinations')
    # ### end Alembic commands ###
