"""Compile the schema to PostgreSQL DDL without a database.

This proves the models are real Postgres rather than plausible-looking Python —
JSONB columns, UUID primary keys and every CHECK constraint have to compile.
The initial Alembic revision is autogenerated in Gate 2 against a live
Postgres; until then this is how the schema is verified in CI.
"""

from __future__ import annotations

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "packages" / "contracts"))

from preflight_contracts.models import Base  # noqa: E402
from sqlalchemy.dialects import postgresql  # noqa: E402
from sqlalchemy.schema import CreateIndex, CreateTable  # noqa: E402


def main() -> int:
    dialect = postgresql.dialect()
    checks = 0

    for table in Base.metadata.sorted_tables:
        print(str(CreateTable(table).compile(dialect=dialect)).strip() + ";\n")
        for index in table.indexes:
            print(str(CreateIndex(index).compile(dialect=dialect)).strip() + ";")
        checks += sum(
            1 for c in table.constraints if type(c).__name__ == "CheckConstraint"
        )

    tables = len(Base.metadata.sorted_tables)
    print(f"\n-- {tables} tables, {checks} check constraints compiled for PostgreSQL",
          file=sys.stderr)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
